# Project settings
OBJNAME :=		dsvm
SRCFLDRS :=		src src/interp src/lib src/parser
INCFLDRS :=		include/interp include/lib include/parser
CC :=			gcc
CFLAGS :=		-g -Wall

# Autogenerated settings
SRC :=			$(foreach folder,$(SRCFLDRS),$(wildcard $(folder)/*.c))
HFILES :=		$(foreach folder,$(INCFLDRS),$(wildcard $(folder)/*.h))
INC :=			$(addprefix -I,$(INCFLDRS))

# Build targets
$(OBJNAME) : $(SRC) $(HFILES)
	$(CC) $(INC) $(CFLAGS) -o $(OBJNAME) $(SRC)

.PHONY : clean
clean :
	rm -rf $(OBJNAME)
